<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>apple</name>
   <tag></tag>
   <elementGuidId>0fb6fdca-51b5-4480-94f0-791951904dfd</elementGuidId>
   <imagePath>a-bite-in-the-apple.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>a-bite-in-the-apple.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
