<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_apple</name>
   <tag></tag>
   <elementGuidId>22f6213b-aac5-4a80-8bae-9da4a81dd38d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@id='apple']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@id='apple']</value>
      <webElementGuid>bc20e2e9-e288-47bf-a399-293e5f08e42d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
